#!/usr/bin/env bash
# scripts/hpc_bootstrap.sh
# ------------------------
# Runs on the HPC login node (invoked by scripts/hpc_launch.sh over SSH).
# Idempotent — safe to run repeatedly.
#
# Steps:
#   1. Create python venv at ${HPC_PROJECT_DIR}/.venv if missing.
#   2. Offline pip install from the rsync'd wheels/ directory.
#   3. Write .env with the Telegram / relay / wandb env values.
#   4. mkdir logs, checkpoints, wandb.
#
# This script is *invoked* on the HPC, not run there interactively. All
# required config is passed via env vars — see the "required env" block below.

set -euo pipefail

: "${HPC_PROJECT_DIR:?HPC_PROJECT_DIR must be set}"
: "${LAB_TUNNEL_PORT:?LAB_TUNNEL_PORT must be set}"

cd "${HPC_PROJECT_DIR}"

echo "=========================================="
echo " HPC bootstrap"
echo "  cwd    : $(pwd)"
echo "  host   : $(hostname)"
echo "  user   : $(whoami)"
echo "  python : $(command -v python3 || echo 'MISSING')"
echo "=========================================="

# --- 1. venv --------------------------------------------------------------
if [[ ! -d .venv ]]; then
    echo ">>> creating .venv/"
    python3 -m venv .venv
fi

# shellcheck source=/dev/null
source .venv/bin/activate
echo ">>> venv python: $(which python)"
python -m pip install --upgrade --no-index --find-links wheels/ pip 2>/dev/null || \
    echo "    (pip self-upgrade skipped: no matching wheel — safe to ignore)"

# --- 2. offline pip install ----------------------------------------------
if [[ -d wheels && $(ls wheels/*.whl 2>/dev/null | wc -l) -gt 0 ]]; then
    echo ">>> installing requirements from wheels/ (offline)"
    python -m pip install --no-index --find-links wheels/ -r requirements.txt
else
    echo "!!! wheels/ directory missing or empty — did rsync run?"
    exit 3
fi

# --- 3. write .env --------------------------------------------------------
# ${TELEGRAM_BOT_TOKEN}, ${TELEGRAM_CHAT_ID}, ${LAB_TUNNEL_PORT} come from
# the launcher's env. TELEGRAM_RELAY_URL is *localhost* on the HPC login node —
# but training runs on compute (no reverse tunnel there), so the compute job
# writes to logs/notify_queue.jsonl and the login-node forwarder drains it.
echo ">>> writing .env"
cat > .env <<EOF
# Auto-generated by scripts/hpc_bootstrap.sh — do not commit.
TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-}
TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID:-}
# NOTE: compute nodes cannot reach the login-node tunnel. TELEGRAM_RELAY_URL
# is intentionally left blank inside the compute job's env so that the
# notifier falls through to logs/notify_queue.jsonl. The login-node
# forwarder (scripts/notify_forwarder.py) drains that queue over the tunnel.
TELEGRAM_RELAY_URL=
WANDB_API_KEY=${WANDB_API_KEY:-}
WANDB_MODE=offline
WANDB_PROJECT=${WANDB_PROJECT:-hsi-pi-vae}
WANDB_ENTITY=${WANDB_ENTITY:-}
EOF
chmod 600 .env

# --- 4. directories -------------------------------------------------------
mkdir -p logs checkpoints wandb model
: > logs/notify_queue.jsonl   # ensure it exists

# --- 5. exec bits ---------------------------------------------------------
chmod +x scripts/*.sh scripts/*.pbs 2>/dev/null || true

echo ">>> bootstrap complete."
python - <<'PY'
import sys
print(f"    python : {sys.version.splitlines()[0]}")
import torch
print(f"    torch  : {torch.__version__}  cuda_available: {torch.cuda.is_available()}")
PY
